
countries.desc <- list("code.WD2" =  c( "FR",
                                        "EU",
                                        "US",
                                        "CH",
                                        "NA",
                                        "SA",
                                        "AF",
                                        "RU",
                                        "EUR",
                                        "AS",
                                        "ME"), 
                       "labels.WD2" = c( "France",
                                         "European Union",
                                         "USA",
                                         "China",
                                         "North-America",
                                         "South-America",
                                         "Africa",
                                         "Russia",
                                         "Europe (wt EU)",
                                         "Asia & Oceana",
                                         "Middle-East"))