
countries.desc <- list("code.WD2" =  c( "FR",
                                        "EU",
                                        "US",
                                        "CH",
                                        "NA",
                                        "SA",
                                        "AF",
                                        "RU",
                                        "EUR",
                                        "AS",
                                        "ME"), 
                       "labels.WD2" = c( "France",
                                         "European Union",
                                         "USA",
                                         "China",
                                         "North-America",
                                         "South-America",
                                         "Africa",
                                         "Russia",
                                         "Europe (wt EU)",
                                         "Asia & Oceana",
                                         "Middle-East"))

countries_EU3.desc <- list("code.EU3" =  c( "FR",
                                            "EU",
                                            "WE",
                                            "US",
                                            "CN",
                                            "WF",
                                            "WL",
                                            "WM",
                                            "WA"), 
                           
                           "labels.EU3" = c( "France",
                                             "European Union",
                                             "Europe (others)",
                                             "United States",
                                             "China",
                                             "Asia & Pacific",
                                             "America",
                                             "RoW Middle East",
                                             "RoW Africa"))

countries_EU4.desc <- list("code.EU4" =  c("EU",
                                           "WE",
                                           "US",
                                           "CN",
                                           "WF",
                                           "WL",
                                           "WM",
                                           "WA"), 
                           
                           "labels.EU4" = c("European Union",
                                            "Europe (others)",
                                            "United States",
                                            "China",
                                            "Asia & Pacific",
                                            "America",
                                            "RoW Middle East",
                                            "RoW Africa"))