
countries.desc_WD2 <- list("codes"         = c("FR",
                                               "EU",
                                               "US",
                                               "CH",
                                               "NA",
                                               "SA",
                                               "AF",
                                               "RU",
                                               "EUR",
                                               "AS",
                                               "ME"), 
                           "labels_en"     = c("France",
                                               "European Union",
                                               "USA",
                                               "China",
                                               "North-America",
                                               "South-America",
                                               "Africa",
                                               "Russia",
                                               "Europe (wt EU)",
                                               "Asia & Oceana",
                                               "Middle-East"),
                           "labels_fr"     = c("France",
                                               "Union Européenne",
                                               "USA",
                                               "Chine",
                                               "Amerique du Nord",
                                               "Amérique du Sud",
                                               "Afrique",
                                               "Russie",
                                               "Europe (hors UE)",
                                               "Asie & Océanie",
                                               "Moyen-Orient")
)

countries_EU3.desc <- list("codes"     = c("FR",
                                           "EU",
                                           "WE",

                                           "CN",
                                           "WF",
                                           "US",
                                           "WL",
                                           "WM",
                                           "WA"), 
                           
                           "labels_en" = c("France",
                                           "European Union",
                                           "Europe (others)",
                                           "China",
                                           "Asia & Pacific",
                                           "United States",
                                           "America",
                                           "RoW Middle East",
                                           "RoW Africa"),
                           "labels_fr" = c("France",
                                           "Union Européenne",
                                           "Europe (hors UE)",
                                           "Chine",
                                           "Asie et Pacifique",
                                           "Etats-Unis",
                                           "Amériques (hors USA)",
                                           "Moyen-Orient",
                                           "Afrique")
)

countries_EU4.desc <- list("codes"    =  c("EU",
                                           "WE",
                                           "US",
                                           "CN",
                                           "WF",
                                           "WL",
                                           "WM",
                                           "WA"), 
                           "labels_en" = c("European Union",
                                           "Europe (others)",
                                           "United States",
                                           "China",
                                           "Asia & Pacific",
                                           "America",
                                           "RoW Middle East",
                                           "RoW Africa"),
                           "labels_fr" = c("Union Européenne",
                                           "Europe (hors UE)",
                                           "Etats-Unis",
                                           "Chine",
                                           "Asie et Pacifique",
                                           "Amériques (hors USA)",
                                           "Moyen-Orient",
                                           "Afrique")
)