CPA1.desc <- list("nProducts" = 17,
                  "produits" =   c("Produits agricoles et forestiers",
                                   "Produits de la peche et de l'aquaculture",
                                   "Produits d'extraction",
                                   "Produits manufactures",
                                   "Electricite, gaz et eau",
                                   "Travaux de construction",
                                   "Vente; reparation automobiles et d'articles domestiques",
                                   "Services d'hotellerie et de restauration",
                                   "Transports et communications",
                                   "Services financiers",
                                   "services immobiliers, de location et aux entreprises",
                                   "Services d'administration publique",
                                   "Education",
                                   "Services de sante et d'action sociale",
                                   "Services collectifs, sociaux et personnels",
                                   "Activite des menages",
                                   "Services extra-territoriaux"),
                  "codes"=   c("A",
                               "B",
                               "C",
                               "D",
                               "E",
                               "F",
                               "G",
                               "H",
                               "I",
                               "J",
                               "K",
                               "L",
                               "M",
                               "N",
                               "O",
                               "P",
                               "Q"))