CPA2.desc <- list("nProducts" = 31,
                  "produits" =  c("Produits agricoles et forestiers",
                                  "Produits de la peche et de l'aquaculture",
                                  "Produits d'extraction energetiques",
                                  "Produits d'extraction non energetiques",
                                  "Produits des industries agricoles et alimentaires",
                                  "Produits de l'industrie textile et de l'habillement",
                                  "Cuirs, articles de voyage, chaussures",
                                  "Produits du travail du bois",
                                  "Papiers et cartons; produits edites, imprimes ou reproduits",
                                  "Produits de la cokefaction, du raffinage et des industries nucleaires",
                                  "Produits chimiques",
                                  "Produits en caoutchouc ou en plastique",
                                  "Autres produits mineraux non metalliques",
                                  "Produits de la metallurgie et du travail des metaux" ,
                                  "Machines et equipements",
                                  "Equipements electriques et electroniques",
                                  "Materiel de transport",
                                  "Autres produits manufactures",
                                  "Electricite, gaz et eau",
                                  "Travaux de construction",
                                  "Ventes; Reparations automobiles et d'articles domestiques",
                                  "Services d'hotellerie et de restauration",
                                  "Transports et communications",
                                  "Services financiers",
                                  "Services immobiliers, de location et aux entreprises",
                                  "Service d'administration publique",
                                  "Education",
                                  "Services de sante et d'action sociale",
                                  "Services collectifs, sociaux et personnels",
                                  "Activite des menages",
                                  "Services extra-territoriaux"),
                  "codes" =  c("A",
                               "BA",
                               "CA",
                               "CB",
                               "DA",
                               "DB",
                               "DC",
                               "DD",
                               "DE",
                               "DF",
                               "DG",
                               "DH",
                               "DI",
                               "DJ",
                               "DK",
                               "DL",
                               "DM",
                               "DN",
                               "EA",
                               "FA",
                               "GA",
                               "HA",
                               "IA",
                               "JA",
                               "KA",
                               "LA",
                               "MA",
                               "NA",
                               "OA",
                               "PA",
                               "QA"))
