# Description of the sectors and products included in Exiobase 2

# Number of sectors and products in Exiobase 2
CPA3.desc <- list("nProducts" = 62,
                  "produits" =  c("Produits de la culture et de l'elevage",
                                  "Produits sylvicoles",
                                  "Produits de la peche et de l'aquaculture",
                                  "Houille, lignite et tourbe",
                                  "Hydrocarbures naturels",
                                  "Minerais d'uranium",
                                  "Minerais metalliques",
                                  "Produits divers des industries extractives",
                                  "Produits des industries extractives",
                                  "Produits des industries alimentaires",
                                  "Tabac manufacture",
                                  "Produits de l'industrie du textile",
                                  "Articles d'habillement et de fourrures",
                                  "Cuirs, articles de voyage, chaussures",
                                  "Produits du travail du bois",
                                  "Papiers et cartons",
                                  "Produits de la cokefaction, du raffinage et des industries nucleaires",
                                  "Produits chimiques",
                                  "Produits en caoutchouc ou en plastique",
                                  "Autres produits mineraux non metalliques",
                                  "Produits metallurgiques",
                                  "Produits du travail des metaux",
                                  "Machines et equipements",
                                  "Machines de bureau et materiel informatique",
                                  "Machines et appareil electriques",
                                  "Equipements de radio, television et communication",
                                  "Instruments medicaux de precision, d'optique et d'horlogerie",
                                  "Produits de l'industrie automobile",
                                  "Autres materiels de transport",
                                  "Meubles et produits des industries diverses",
                                  "Matieres premieres secondaires",
                                  "Electricite, gaz et eau",
                                  "eau distribuee",
                                  "Travaux de construction",
                                  "Vente et reparation automobile",
                                  "Ventes en gros et services d'intermediaire du commerce de gros",
                                  "Vente au detail et reparation d'articles domestiques",
                                  "Services d'hotellerie et de restauration",
                                  "Transports terrestres",
                                  "Transports par eaux",
                                  "Transports aeriens",
                                  "Services auxiliaires des transports",
                                  "Services des postes et telecommunications",
                                  "Intermediation financiere",
                                  "Assurance",
                                  "Services d'auxiliaires financiers et d'assurance",
                                  "Services immobiliers",
                                  "Location sans operateur",
                                  "Services informatiques",
                                  "Recherche et developpement",
                                  "Services fournis principalement aux entreprises",
                                  "Services d'administration publique",
                                  "Education",
                                  "Services de sante et d'action sociale",
                                  "Assainissement, voirie et gestion des dechets",
                                  "Services fournis par les organisations associatives",
                                  "Services recreatifs, culturels et sportifs",
                                  "Services personnels",
                                  "Activite des menages en tant qu'employeur du personnel domestique",
                                  "Biens divers produits par les menages prives pour leur consommation propre",
                                  "Services divers produits par les menages prives pour leur consommation propre",
                                  "Services extra-territoriaux"),
                  "codes" =  c("01",
                                   "02",
                                   "05",
                                   "10",
                                   "11",
                                   "12",
                                   "13",
                                   "14",
                                   "15",
                                   "16",
                                   "17",
                                   "18",
                                   "19",
                                   "20",
                                   "21",
                                   "22",
                                   "23",
                                   "24",
                                   "25",
                                   "26",
                                   "27",
                                   "28",
                                   "29",
                                   "30",
                                   "31",
                                   "32",
                                   "33",
                                   "34",
                                   "35",
                                   "36",
                                   "37",
                                   "40",
                                   "41",
                                   "45",
                                   "50",
                                   "51",
                                   "52",
                                   "55",
                                   "60",
                                   "61",
                                   "62",
                                   "63",
                                   "64",
                                   "65",
                                   "66",
                                   "67",
                                   "70",
                                   "71",
                                   "72",
                                   "73",
                                   "74",
                                   "75",
                                   "80",
                                   "85",
                                   "90",
                                   "91",
                                   "92",
                                   "93",
                                   "95",
                                   "96",
                                   "97",
                                   "99"))
