# Description of the sectors and products included in Exiobase 2

# Number of sectors and products in Exiobase 2
CPA4.desc <- list("nProducts" = 223,
                  "products" =  c(
                    "Produits de la culture",
                    "Produits de l'elevage",
                    "Services annexes a l'agriculture",
                    "Services annexes a la chasse",
                    "Produits sylvicoles",
                    "Produits de la peche et de l'aquaculture",
                    "Houille",
                    "Lignite",
                    "Tourbe",
                    "Petrole brut et gaz naturel",
                    "Services annexes a l'extraction d'hydrocarbures",
                    "Minerais d'uranium",
                    "Minerais de fer",
                    "Minerais de metaux non ferreux",
                    "Pierres pour la construction et l'industrie",
                    "Sables et argiles",
                    "Mineraux pour l'industrie chimique et engrais naturels",
                    "Sel",
                    "Autres produits mineraux n.c.a.",
                    "Viandes, peaux et produits a base de viandes",
                    "Poissons et produits de la peche prepares",
                    "Produits a base de fruits et legumes",
                    "Huiles, tourteaux et corps gras",
                    "Produits laitiers et glaces",
                    "Farines, cereales transformees et produits amylaces",
                    "Aliments pour animaux",
                    "Autres produits alimentaires",
                    "Boissons",
                    "Tabac manufacture",
                    "Fils et files",
                    "Tissus",
                    "Ennoblissement textile",
                    "Articles textiles",
                    "Autres produits textiles",
                    "etoffes a maille",
                    "Articles a maille",
                    "Vetements en cuir",
                    "Vetements en textile",
                    "Pelleteries et fourrures",
                    "Cuirs travailles",
                    "Articles de voyage et de maroquinerie",
                    "Chaussures et articles chaussants",
                    "Produits du sciage",
                    "Panneaux et placages a base de bois",
                    "Charpentes et menuiseries de batiment, en bois",
                    "Emballages en bois",
                    "Objets divers en bois, liege ou vannerie",
                    "Pate a papier, papiers et cartons",
                    "Articles en papier ou en carton",
                    "Produits de l'edition",
                    "Produits de l'imprimerie",
                    "Reproduction d'enregistrements",
                    "Cokes et goudrons",
                    "Produits petroliers raffines",
                    "Produits des industries nucleaires",
                    "Produits chimiques de base",
                    "Produits agrochimiques",
                    "Peintures, vernis, adjuvants, encres d'imprimerie",
                    "Produits pharmaceutiques",
                    "Savons, parfums et produits d'entretien",
                    "Autres produits chimiques",
                    "Fibres artificielles ou synthetiques",
                    "Produits en caoutchouc",
                    "Produits en matieres plastiques",
                    "Verre et articles en verre",
                    "Produits ceramiques",
                    "Carreaux en ceramique",
                    "Tuiles et briques en terre cuite",
                    "Ciment, chaux et platre",
                    "Ouvrages en beton ou en platre",
                    "Ouvrages en pierre taillee et autrement façonnee ",
                    "Produits mineraux divers",
                    "Produits siderurgiques",
                    "Tubes et tuyaux",
                    "Produits de la transformation de l'acier",
                    "Metaux non ferreux",
                    "Pieces de fonderie",
                    "elements en metal pour la construction",
                    "Reservoirs; chaudieres pour le chauffage central",
                    "Produits de la chaudronnerie",
                    "Produits de la forge, de l'emboutissage et du frittage",
                    "Traitement des metaux et mecanique generale",
                    "Coutellerie, outillage et quincaillerie",
                    "Autres ouvrages en metaux",
                    "equipements mecaniques",
                    "Machines d'usage general",
                    "Machines agricoles",
                    "Machines-outils",
                    "Autres machines d'usage specifique",
                    "Armes et munitions",
                    "Appareils domestiques",
                    "Machines de bureau et materiel informatique",
                    "Moteurs, generatrices et transformateurs electriques",
                    "Materiel de distribution et de commande electrique",
                    "Fils et cables isoles",
                    "Accumulateurs et piles electriques",
                    "Lampes et appareils d'eclairage",
                    "Autres materiels electriques",
                    "Composants electroniques",
                    "Appareils d'emission et de transmission du son et de l'image",
                    "Appareils de reception, enregistrement ou reproduction du son et de l'image",
                    "Materiel medicochirurgical et d'orthopedie",
                    "Instruments de mesure et de contrôle",
                    "Contrôle automatique de processus industriels",
                    "Materiels optique et photographique",
                    "Montres, pendules et horloges",
                    "Vehicules automobiles",
                    "Carrosseries et remorques",
                    "equipements automobiles",
                    "Produits de la construction navale",
                    "Materiel ferroviaire roulant",
                    "Produits de la construction aeronautique et spatiale",
                    "Motocycles et bicyclettes",
                    "Materiels de transport n.c.a.",
                    "Meubles",
                    "Monnaies et bijoux",
                    "Instruments de musique",
                    "Articles de sport",
                    "Jeux et jouets",
                    "Produits des autres industries diverses",
                    "Matieres premieres secondaires metalliques",
                    "Matieres premieres secondaires non metalliques",
                    "electricite",
                    "Combustibles gazeux distribues",
                    "Supports energetiques",
                    "Eau distribuee",
                    "Travaux de preparation des sites",
                    "Travaux de construction d'ouvrages de batiment ou de genie civil",
                    "Travaux d'installation",
                    "Travaux de finition",
                    "Location avec operateur de materiel de construction",
                    "Vente de vehicules automobiles",
                    "Entretien et reparation de vehicules automobiles",
                    "Vente d'equipements automobiles",
                    "Vente et reparation de motocycles",
                    "Vente au detail de carburant",
                    "Services d'intermediaire du commerce de gros",
                    "Vente en gros de produits agricoles bruts",
                    "Vente en gros de produits alimentaires",
                    "Vente en gros de biens de consommation non alimentaire",
                    "Vente en gros de produits intermediaires non agricoles",
                    "Vente en gros d'equipements industriels",
                    "Autres ventes en gros",
                    "Vente au detail en magasin non specialise",
                    "Vente au detail de produits alimentaires",
                    "Vente au detail de produits pharmaceutiques et de parfumerie",
                    "Vente au detail d'autres biens de consommation",
                    "Vente au detail de biens d'occasion",
                    "Vente au detail hors magasin",
                    "Reparation d'articles personnels et domestiques",
                    "Hebergement hôtelier",
                    "Autres hebergements de courte duree",
                    "Services de restauration",
                    "Services des debits de boissons",
                    "Services des cantines et traiteurs",
                    "Transports ferroviaires",
                    "Transports urbains et routiers",
                    "Transports par conduites",
                    "Transports maritimes et côtiers",
                    "Transports fluviaux",
                    "Transports aeriens reguliers",
                    "Transports aeriens non reguliers",
                    "Transports spatiaux",
                    "Services de manutention et d'entreposage",
                    "Gestion d'infrastructures de transports",
                    "Services des agences de voyage",
                    "Organisation du transport de fret",
                    "Services de poste et de courrier",
                    "Services de telecommunications",
                    "Services d'intermediation monetaire",
                    "Autres services d'intermediation financiere",
                    "Assurance",
                    "Services d'auxiliaires financiers",
                    "Services d'auxiliaires d'assurance",
                    "Services immobiliers pour compte propre",
                    "Location de biens immobiliers",
                    "Services immobiliers pour compte de tiers",
                    "Location de vehicules automobiles",
                    "Location d'autres materiels de transport",
                    "Location de machines et equipements",
                    "Location de biens personnels et domestiques",
                    "Services de conseils en configurations informatiques",
                    "Developpements logiciels",
                    "Services de traitement de donnees",
                    "Services des banques de donnees",
                    "Entretien et reparation de machines de bureau et de materiel informatique",
                    "Autres services rattaches a l'informatique",
                    "Recherche-developpement en sciences physiques et naturelles",
                    "Recherche-developpement en sciences humaines et sociales",
                    "Services juridiques, comptables et de conseil de gestion",
                    "Services d'architecture et d'ingenierie",
                    "Contrôle et analyses techniques",
                    "Publicite",
                    "Selection et fourniture de personnel",
                    "Enquetes et securite",
                    "Service de nettoyage",
                    "Services divers fournis principalement aux entreprises",
                    "Administration generale, economique et sociale",
                    "Services de prerogative publique",
                    "Service de securite sociale",
                    "Enseignement primaire",
                    "Enseignement secondaire",
                    "Enseignement superieur",
                    "Formation permanente et autres services d'enseignement",
                    "Services relatifs a la sante humaine",
                    "Services veterinaires",
                    "Services d'action sociale",
                    "Assainissement, voirie et gestion des dechets",
                    "Services fournis par les organisations economiques",
                    "Services fournis par les syndicats de salaries",
                    "Services fournis par les autres organisations associatives",
                    "Films et services cinematographiques",
                    "Services de radio et de television",
                    "Services du spectacle",
                    "Services des agences de presse",
                    "Autres services culturels",
                    "Services lies au sport",
                    "Services recreatifs",
                    "Services personnels",
                    "Activites des menages en tant qu'employeur de personnel domestique ",
                    "Biens divers produits par les menages prives pour leur consommation propre",
                    "Services divers produits par les menages prives pour leur consommation propre",
                    "Services extra-territoriaux"),
                    "codes" =  c(
                                   "1.1",
                                   "01.2",
                                   "01.4",
                                   "01.5",
                                   "02.0",
                                   "05.0",
                                   "10.1",
                                   "10.2",
                                   "10.3",
                                   "11.1",
                                   "11.2",
                                   "12.0",
                                   "13.1",
                                   "13.2",
                                   "14.1",
                                   "14.2",
                                   "14.3",
                                   "14.4",
                                   "14.5",
                                   "15.1",
                                   "15.2",
                                   "15.3",
                                   "15.4",
                                   "15.5",
                                   "15.6",
                                   "15.7",
                                   "15.8",
                                   "15.9",
                                   "16.0",
                                   "17.1",
                                   "17.2",
                                   "17.3",
                                   "17.4",
                                   "17.5",
                                   "17.6",
                                   "17.7",
                                   "18.1",
                                   "18.2",
                                   "18.3",
                                   "19.1",
                                   "19.2",
                                   "19.3",
                                   "20.1",
                                   "20.2",
                                   "20.3",
                                   "20.4",
                                   "20.5",
                                   "21.1",
                                   "21.2",
                                   "22.1",
                                   "22.2",
                                   "22.3",
                                   "23.1",
                                   "23.2",
                                   "23.3",
                                   "24.1",
                                   "24.2",
                                   "24.3",
                                   "24.4",
                                   "24.5",
                                   "24.6",
                                   "24.7",
                                   "25.1",
                                   "25.2",
                                   "26.1",
                                   "26.2",
                                   "26.3",
                                   "26.4",
                                   "26.5",
                                   "26.6",
                                   "26.7",
                                   "26.8",
                                   "27.1",
                                   "27.2",
                                   "27.3",
                                   "27.4",
                                   "27.5",
                                   "28.1",
                                   "28.2",
                                   "28.3",
                                   "28.4",
                                   "28.5",
                                   "28.6",
                                   "28.7",
                                   "29.1",
                                   "29.2",
                                   "29.3",
                                   "29.4",
                                   "29.5",
                                   "29.6",
                                   "29.7",
                                   "30.0",
                                   "31.1",
                                   "31.2",
                                   "31.3",
                                   "31.4",
                                   "31.5",
                                   "31.6",
                                   "32.1",
                                   "32.2",
                                   "32.3",
                                   "33.1",
                                   "33.2",
                                   "33.3",
                                   "33.4",
                                   "33.5",
                                   "34.1",
                                   "34.2",
                                   "34.3",
                                   "35.1",
                                   "35.2",
                                   "35.3",
                                   "35.4",
                                   "35.5",
                                   "36.1",
                                   "36.2",
                                   "36.3",
                                   "36.4",
                                   "36.5",
                                   "36.6",
                                   "37.1",
                                   "37.2",
                                   "40.1",
                                   "40.2",
                                   "40.3",
                                   "41.0",
                                   "45.1",
                                   "45.2",
                                   "45.3",
                                   "45.4",
                                   "45.5",
                                   "50.1",
                                   "50.2",
                                   "50.3",
                                   "50.4",
                                   "50.5",
                                   "51.1",
                                   "51.2",
                                   "51.3",
                                   "51.4",
                                   "51.5",
                                   "51.8",
                                   "51.9",
                                   "52.1",
                                   "52.2",
                                   "52.3",
                                   "52.4",
                                   "52.5",
                                   "52.6",
                                   "52.7",
                                   "55.1",
                                   "55.2",
                                   "55.3",
                                   "55.4",
                                   "55.5",
                                   "60.1",
                                   "60.2",
                                   "60.3",
                                   "61.1",
                                   "61.2",
                                   "62.1",
                                   "62.2",
                                   "62.3",
                                   "63.1",
                                   "63.2",
                                   "63.3",
                                   "63.4",
                                   "64.1",
                                   "64.2",
                                   "65.1",
                                   "65.2",
                                   "66.0",
                                   "67.1",
                                   "67.2",
                                   "70.1",
                                   "70.2",
                                   "70.3",
                                   "71.1",
                                   "71.2",
                                   "71.3",
                                   "71.4",
                                   "72.1",
                                   "72.2",
                                   "72.3",
                                   "72.4",
                                   "72.5",
                                   "72.6",
                                   "73.1",
                                   "73.2",
                                   "74.1",
                                   "74.2",
                                   "74.3",
                                   "74.4",
                                   "74.5",
                                   "74.6",
                                   "74.7",
                                   "74.8",
                                   "75.1",
                                   "75.2",
                                   "75.3",
                                   "80.1",
                                   "80.2",
                                   "80.3",
                                   "80.4",
                                   "85.1",
                                   "85.2",
                                   "85.3",
                                   "90.0",
                                   "91.1",
                                   "91.2",
                                   "91.3",
                                   "92.1",
                                   "92.2",
                                   "92.3",
                                   "92.4",
                                   "92.5",
                                   "92.6",
                                   "92.7",
                                   "93.0",
                                   "95.0",
                                   "96.0",
                                   "97.0",
                                   "99.0"))
