# Description of the sectors and products included in Exiobase 3

# Number of sectors and products in Exiobase 3
exio3.desc <- list("nSectors" = 163,
                   "nProducts" = 200,
                   "nCountries" = 49,
                   "sectors" =
                     c("Cultivation of paddy rice",
                       "Cultivation of wheat",
                       "Cultivation of cereal grains nec",
                       "Cultivation of vegetables, fruit, nuts",
                       "Cultivation of oil seeds",
                       "Cultivation of sugar cane, sugar beet",
                       "Cultivation of plant-based fibers",
                       "Cultivation of crops nec",
                       "Cattle farming",
                       "Pigs farming",
                       "Poultry farming",
                       "Meat animals nec",
                       "Animal products nec",
                       "Raw milk",
                       "Wool, silk-worm cocoons",
                       "Manure treatment (conventional), storage and land application",
                       "Manure treatment (biogas), storage and land application",
                       "Forestry, logging and related service activities",
                       "Fishing, operating of fish hatcheries and fish farms; service activities incidental to fishing",
                       "Mining of coal and lignite; extraction of peat",
                       "Extraction of crude petroleum and services related to crude oil extraction, excluding surveying",
                       "Extraction of natural gas and services related to natural gas extraction, excluding surveying",
                       "Extraction, liquefaction, and regasification of other petroleum and gaseous materials",
                       "Mining of uranium and thorium ores",
                       "Mining of iron ores",
                       "Mining of copper ores and concentrates",
                       "Mining of nickel ores and concentrates",
                       "Mining of aluminium ores and concentrates",
                       "Mining of precious metal ores and concentrates",
                       "Mining of lead, zinc and tin ores and concentrates",
                       "Mining of other non-ferrous metal ores and concentrates",
                       "Quarrying of stone",
                       "Quarrying of sand and clay",
                       "Mining of chemical and fertilizer minerals, production of salt, other mining and quarrying n.e.c.",
                       "Processing of meat cattle",
                       "Processing of meat pigs",
                       "Processing of meat poultry",
                       "Production of meat products nec",
                       "Processing vegetable oils and fats",
                       "Processing of dairy products",
                       "Processed rice",
                       "Sugar refining",
                       "Processing of Food products nec",
                       "Manufacture of beverages",
                       "Manufacture of fish products",
                       "Manufacture of tobacco products",
                       "Manufacture of textiles",
                       "Manufacture of wearing apparel; dressing and dyeing of fur",
                       "Tanning and dressing of leather; manufacture of luggage, handbags, saddlery, harness and footwear",
                       "Manufacture of wood and of products of wood and cork, except furniture; manufacture of articles of straw and plaiting materials",
                       "Re-processing of secondary wood material into new wood material",
                       "Pulp",
                       "Re-processing of secondary paper into new pulp",
                       "Paper",
                       "Publishing, printing and reproduction of recorded media",
                       "Manufacture of coke oven products",
                       "Petroleum Refinery",
                       "Processing of nuclear fuel",
                       "Plastics, basic",
                       "Re-processing of secondary plastic into new plastic",
                       "N-fertiliser",
                       "P- and other fertiliser",
                       "Chemicals nec",
                       "Manufacture of rubber and plastic products",
                       "Manufacture of glass and glass products",
                       "Re-processing of secondary glass into new glass",
                       "Manufacture of ceramic goods",
                       "Manufacture of bricks, tiles and construction products, in baked clay",
                       "Manufacture of cement, lime and plaster",
                       "Re-processing of ash into clinker",
                       "Manufacture of other non-metallic mineral products n.e.c.",
                       "Manufacture of basic iron and steel and of ferro-alloys and first products thereof",
                       "Re-processing of secondary steel into new steel",
                       "Precious metals production",
                       "Re-processing of secondary preciuos metals into new preciuos metals",
                       "Aluminium production",
                       "Re-processing of secondary aluminium into new aluminium",
                       "Lead, zinc and tin production",
                       "Re-processing of secondary lead into new lead",
                       "Copper production",
                       "Re-processing of secondary copper into new copper",
                       "Other non-ferrous metal production",
                       "Re-processing of secondary other non-ferrous metals into new other non-ferrous metals",
                       "Casting of metals",
                       "Manufacture of fabricated metal products, except machinery and equipment",
                       "Manufacture of machinery and equipment n.e.c.",
                       "Manufacture of office machinery and computers",
                       "Manufacture of electrical machinery and apparatus n.e.c.",
                       "Manufacture of radio, television and communication equipment and apparatus",
                       "Manufacture of medical, precision and optical instruments, watches and clocks",
                       "Manufacture of motor vehicles, trailers and semi-trailers",
                       "Manufacture of other transport equipment",
                       "Manufacture of furniture; manufacturing n.e.c.",
                       "Recycling of waste and scrap",
                       "Recycling of bottles by direct reuse",
                       "Production of electricity by coal",
                       "Production of electricity by gas",
                       "Production of electricity by nuclear",
                       "Production of electricity by hydro",
                       "Production of electricity by wind",
                       "Production of electricity by petroleum and other oil derivatives",
                       "Production of electricity by biomass and waste",
                       "Production of electricity by solar photovoltaic",
                       "Production of electricity by solar thermal",
                       "Production of electricity by tide, wave, ocean",
                       "Production of electricity by Geothermal",
                       "Production of electricity nec",
                       "Transmission of electricity",
                       "Distribution and trade of electricity",
                       "Manufacture of gas; distribution of gaseous fuels through mains",
                       "Steam and hot water supply",
                       "Collection, purification and distribution of water",
                       "Construction",
                       "Re-processing of secondary construction material into aggregates",
                       "Sale, maintenance, repair of motor vehicles, motor vehicles parts, motorcycles, motor cycles parts and accessoiries",
                       "Retail sale of automotive fuel",
                       "Wholesale trade and commission trade, except of motor vehicles and motorcycles",
                       "Retail trade, except of motor vehicles and motorcycles; repair of personal and household goods",
                       "Hotels and restaurants",
                       "Transport via railways",
                       "Other land transport",
                       "Transport via pipelines",
                       "Sea and coastal water transport",
                       "Inland water transport",
                       "Air transport",
                       "Supporting and auxiliary transport activities; activities of travel agencies",
                       "Post and telecommunications",
                       "Financial intermediation, except insurance and pension funding",
                       "Insurance and pension funding, except compulsory social security",
                       "Activities auxiliary to financial intermediation",
                       "Real estate activities",
                       "Renting of machinery and equipment without operator and of personal and household goods",
                       "Computer and related activities",
                       "Research and development",
                       "Other business activities",
                       "Public administration and defence; compulsory social security",
                       "Education",
                       "Health and social work",
                       "Incineration of waste: Food",
                       "Incineration of waste: Paper",
                       "Incineration of waste: Plastic",
                       "Incineration of waste: Metals and Inert materials",
                       "Incineration of waste: Textiles",
                       "Incineration of waste: Wood",
                       "Incineration of waste: Oil/Hazardous waste",
                       "Biogasification of food waste, incl. land application",
                       "Biogasification of paper, incl. land application",
                       "Biogasification of sewage slugde, incl. land application",
                       "Composting of food waste, incl. land application",
                       "Composting of paper and wood, incl. land application",
                       "Waste water treatment, food",
                       "Waste water treatment, other",
                       "Landfill of waste: Food",
                       "Landfill of waste: Paper",
                       "Landfill of waste: Plastic",
                       "Landfill of waste: Inert/metal/hazardous",
                       "Landfill of waste: Textiles",
                       "Landfill of waste: Wood",
                       "Activities of membership organisation n.e.c.",
                       "Recreational, cultural and sporting activities",
                       "Other service activities",
                       "Private households with employed persons",
                       "Extra-territorial organizations and bodies"),
                   
                   "products" =
                     c("Paddy rice",
                       "Wheat",
                       "Cereal grains nec",
                       "Vegetables, fruit, nuts",
                       "Oil seeds",
                       "Sugar cane, sugar beet",
                       "Plant-based fibers",
                       "Crops nec",
                       "Cattle",
                       "Pigs",
                       "Poultry",
                       "Meat animals nec",
                       "Animal products nec",
                       "Raw milk",
                       "Wool, silk-worm cocoons",
                       "Manure (conventional treatment)",
                       "Manure (biogas treatment)",
                       "Products of forestry, logging and related services",
                       "Fish and other fishing products; services incidental of fishing",
                       "Anthracite",
                       "Coking Coal",
                       "Other Bituminous Coal",
                       "Sub-Bituminous Coal",
                       "Patent Fuel",
                       "Lignite/Brown Coal",
                       "BKB/Peat Briquettes",
                       "Peat",
                       "Crude petroleum and services related to crude oil extraction, excluding surveying",
                       "Natural gas and services related to natural gas extraction, excluding surveying",
                       "Natural Gas Liquids",
                       "Other Hydrocarbons",
                       "Uranium and thorium ores",
                       "Iron ores",
                       "Copper ores and concentrates",
                       "Nickel ores and concentrates",
                       "Aluminium ores and concentrates",
                       "Precious metal ores and concentrates",
                       "Lead, zinc and tin ores and concentrates",
                       "Other non-ferrous metal ores and concentrates",
                       "Stone",
                       "Sand and clay",
                       "Chemical and fertilizer minerals, salt and other mining and quarrying products n.e.c.",
                       "Products of meat cattle",
                       "Products of meat pigs",
                       "Products of meat poultry",
                       "Meat products nec",
                       "products of Vegetable oils and fats",
                       "Dairy products",
                       "Processed rice",
                       "Sugar",
                       "Food products nec",
                       "Beverages",
                       "Fish products",
                       "Tobacco products",
                       "Textiles",
                       "Wearing apparel; furs",
                       "Leather and leather products",
                       "Wood and products of wood and cork (except furniture); articles of straw and plaiting materials",
                       "Wood material for treatment, Re-processing of secondary wood material into new wood material",
                       "Pulp",
                       "Secondary paper for treatment, Re-processing of secondary paper into new pulp",
                       "Paper and paper products",
                       "Printed matter and recorded media",
                       "Coke Oven Coke",
                       "Gas Coke",
                       "Coal Tar",
                       "Motor Gasoline",
                       "Aviation Gasoline",
                       "Gasoline Type Jet Fuel",
                       "Kerosene Type Jet Fuel",
                       "Kerosene",
                       "Gas/Diesel Oil",
                       "Heavy Fuel Oil",
                       "Refinery Gas",
                       "Liquefied Petroleum Gases (LPG)",
                       "Refinery Feedstocks",
                       "Ethane",
                       "Naphtha",
                       "White Spirit & SBP",
                       "Lubricants",
                       "Bitumen",
                       "Paraffin Waxes",
                       "Petroleum Coke",
                       "Non-specified Petroleum Products",
                       "Nuclear fuel",
                       "Plastics, basic",
                       "Secondary plastic for treatment, Re-processing of secondary plastic into new plastic",
                       "N-fertiliser",
                       "P- and other fertiliser",
                       "Chemicals nec",
                       "Charcoal",
                       "Additives/Blending Components",
                       "Biogasoline",
                       "Biodiesels",
                       "Other Liquid Biofuels",
                       "Rubber and plastic products",
                       "Glass and glass products",
                       "Secondary glass for treatment, Re-processing of secondary glass into new glass",
                       "Ceramic goods",
                       "Bricks, tiles and construction products, in baked clay",
                       "Cement, lime and plaster",
                       "Ash for treatment, Re-processing of ash into clinker",
                       "Other non-metallic mineral products",
                       "Basic iron and steel and of ferro-alloys and first products thereof",
                       "Secondary steel for treatment, Re-processing of secondary steel into new steel",
                       "Precious metals",
                       "Secondary preciuos metals for treatment, Re-processing of secondary preciuos metals into new preciuos metals",
                       "Aluminium and aluminium products",
                       "Secondary aluminium for treatment, Re-processing of secondary aluminium into new aluminium",
                       "Lead, zinc and tin and products thereof",
                       "Secondary lead for treatment, Re-processing of secondary lead into new lead",
                       "Copper products",
                       "Secondary copper for treatment, Re-processing of secondary copper into new copper",
                       "Other non-ferrous metal products",
                       "Secondary other non-ferrous metals for treatment, Re-processing of secondary other non-ferrous metals into new other non-ferrous metals",
                       "Foundry work services",
                       "Fabricated metal products, except machinery and equipment",
                       "Machinery and equipment n.e.c.",
                       "Office machinery and computers",
                       "Electrical machinery and apparatus n.e.c.",
                       "Radio, television and communication equipment and apparatus",
                       "Medical, precision and optical instruments, watches and clocks",
                       "Motor vehicles, trailers and semi-trailers",
                       "Other transport equipment",
                       "Furniture; other manufactured goods n.e.c.",
                       "Secondary raw materials",
                       "Bottles for treatment, Recycling of bottles by direct reuse",
                       "Electricity by coal",
                       "Electricity by gas",
                       "Electricity by nuclear",
                       "Electricity by hydro",
                       "Electricity by wind",
                       "Electricity by petroleum and other oil derivatives",
                       "Electricity by biomass and waste",
                       "Electricity by solar photovoltaic",
                       "Electricity by solar thermal",
                       "Electricity by tide, wave, ocean",
                       "Electricity by Geothermal",
                       "Electricity nec",
                       "Transmission services of electricity",
                       "Distribution and trade services of electricity",
                       "Coke oven gas",
                       "Blast Furnace Gas",
                       "Oxygen Steel Furnace Gas",
                       "Gas Works Gas",
                       "Biogas",
                       "Distribution services of gaseous fuels through mains",
                       "Steam and hot water supply services",
                       "Collected and purified water, distribution services of water",
                       "Construction work",
                       "Secondary construction material for treatment, Re-processing of secondary construction material into aggregates",
                       "Sale, maintenance, repair of motor vehicles, motor vehicles parts, motorcycles, motor cycles parts and accessoiries",
                       "Retail trade services of motor fuel",
                       "Wholesale trade and commission trade services, except of motor vehicles and motorcycles",
                       "Retail  trade services, except of motor vehicles and motorcycles; repair services of personal and household goods",
                       "Hotel and restaurant services",
                       "Railway transportation services",
                       "Other land transportation services",
                       "Transportation services via pipelines",
                       "Sea and coastal water transportation services",
                       "Inland water transportation services",
                       "Air transport services",
                       "Supporting and auxiliary transport services; travel agency services",
                       "Post and telecommunication services",
                       "Financial intermediation services, except insurance and pension funding services",
                       "Insurance and pension funding services, except compulsory social security services",
                       "Services auxiliary to financial intermediation",
                       "Real estate services",
                       "Renting services of machinery and equipment without operator and of personal and household goods",
                       "Computer and related services",
                       "Research and development services",
                       "Other business services",
                       "Public administration and defence services; compulsory social security services",
                       "Education services",
                       "Health and social work services",
                       "Food waste for treatment: incineration",
                       "Paper waste for treatment: incineration",
                       "Plastic waste for treatment: incineration",
                       "Intert/metal waste for treatment: incineration",
                       "Textiles waste for treatment: incineration",
                       "Wood waste for treatment: incineration",
                       "Oil/hazardous waste for treatment: incineration",
                       "Food waste for treatment: biogasification and land application",
                       "Paper waste for treatment: biogasification and land application",
                       "Sewage sludge for treatment: biogasification and land application",
                       "Food waste for treatment: composting and land application",
                       "Paper and wood waste for treatment: composting and land application",
                       "Food waste for treatment: waste water treatment",
                       "Other waste for treatment: waste water treatment",
                       "Food waste for treatment: landfill",
                       "Paper for treatment: landfill",
                       "Plastic waste for treatment: landfill",
                       "Inert/metal/hazardous waste for treatment: landfill",
                       "Textiles waste for treatment: landfill",
                       "Wood waste for treatment: landfill",
                       "Membership organisation services n.e.c.",
                       "Recreational, cultural and sporting services",
                       "Other services",
                       "Private households with employed persons",
                       "Extra-territorial organizations and bodies"), 
                   "codes" =
                     c("Paddy rice",
                       "Wheat",
                       "Cereal grains nec",
                       "Vegetables, fruit, nuts",
                       "Oil seeds",
                       "Sugar cane, sugar beet",
                       "Plant-based fibers",
                       "Crops nec",
                       "Cattle",
                       "Pigs",
                       "Poultry",
                       "Meat animals nec",
                       "Animal products nec",
                       "Raw milk",
                       "Wool, silk-worm cocoons",
                       "Manure (conventional treatment)",
                       "Manure (biogas treatment)",
                       "Products of forestry, logging and related services",
                       "Fish and other fishing products; services incidental of fishing",
                       "Anthracite",
                       "Coking Coal",
                       "Other Bituminous Coal",
                       "Sub-Bituminous Coal",
                       "Patent Fuel",
                       "Lignite/Brown Coal",
                       "BKB/Peat Briquettes",
                       "Peat",
                       "Crude petroleum and services related to crude oil extraction, excluding surveying",
                       "Natural gas and services related to natural gas extraction, excluding surveying",
                       "Natural Gas Liquids",
                       "Other Hydrocarbons",
                       "Uranium and thorium ores",
                       "Iron ores",
                       "Copper ores and concentrates",
                       "Nickel ores and concentrates",
                       "Aluminium ores and concentrates",
                       "Precious metal ores and concentrates",
                       "Lead, zinc and tin ores and concentrates",
                       "Other non-ferrous metal ores and concentrates",
                       "Stone",
                       "Sand and clay",
                       "Chemical and fertilizer minerals, salt and other mining and quarrying products n.e.c.",
                       "Products of meat cattle",
                       "Products of meat pigs",
                       "Products of meat poultry",
                       "Meat products nec",
                       "products of Vegetable oils and fats",
                       "Dairy products",
                       "Processed rice",
                       "Sugar",
                       "Food products nec",
                       "Beverages",
                       "Fish products",
                       "Tobacco products",
                       "Textiles",
                       "Wearing apparel; furs",
                       "Leather and leather products",
                       "Wood and products of wood and cork (except furniture); articles of straw and plaiting materials",
                       "Wood material for treatment, Re-processing of secondary wood material into new wood material",
                       "Pulp",
                       "Secondary paper for treatment, Re-processing of secondary paper into new pulp",
                       "Paper and paper products",
                       "Printed matter and recorded media",
                       "Coke Oven Coke",
                       "Gas Coke",
                       "Coal Tar",
                       "Motor Gasoline",
                       "Aviation Gasoline",
                       "Gasoline Type Jet Fuel",
                       "Kerosene Type Jet Fuel",
                       "Kerosene",
                       "Gas/Diesel Oil",
                       "Heavy Fuel Oil",
                       "Refinery Gas",
                       "Liquefied Petroleum Gases (LPG)",
                       "Refinery Feedstocks",
                       "Ethane",
                       "Naphtha",
                       "White Spirit & SBP",
                       "Lubricants",
                       "Bitumen",
                       "Paraffin Waxes",
                       "Petroleum Coke",
                       "Non-specified Petroleum Products",
                       "Nuclear fuel",
                       "Plastics, basic",
                       "Secondary plastic for treatment, Re-processing of secondary plastic into new plastic",
                       "N-fertiliser",
                       "P- and other fertiliser",
                       "Chemicals nec",
                       "Charcoal",
                       "Additives/Blending Components",
                       "Biogasoline",
                       "Biodiesels",
                       "Other Liquid Biofuels",
                       "Rubber and plastic products",
                       "Glass and glass products",
                       "Secondary glass for treatment, Re-processing of secondary glass into new glass",
                       "Ceramic goods",
                       "Bricks, tiles and construction products, in baked clay",
                       "Cement, lime and plaster",
                       "Ash for treatment, Re-processing of ash into clinker",
                       "Other non-metallic mineral products",
                       "Basic iron and steel and of ferro-alloys and first products thereof",
                       "Secondary steel for treatment, Re-processing of secondary steel into new steel",
                       "Precious metals",
                       "Secondary preciuos metals for treatment, Re-processing of secondary preciuos metals into new preciuos metals",
                       "Aluminium and aluminium products",
                       "Secondary aluminium for treatment, Re-processing of secondary aluminium into new aluminium",
                       "Lead, zinc and tin and products thereof",
                       "Secondary lead for treatment, Re-processing of secondary lead into new lead",
                       "Copper products",
                       "Secondary copper for treatment, Re-processing of secondary copper into new copper",
                       "Other non-ferrous metal products",
                       "Secondary other non-ferrous metals for treatment, Re-processing of secondary other non-ferrous metals into new other non-ferrous metals",
                       "Foundry work services",
                       "Fabricated metal products, except machinery and equipment",
                       "Machinery and equipment n.e.c.",
                       "Office machinery and computers",
                       "Electrical machinery and apparatus n.e.c.",
                       "Radio, television and communication equipment and apparatus",
                       "Medical, precision and optical instruments, watches and clocks",
                       "Motor vehicles, trailers and semi-trailers",
                       "Other transport equipment",
                       "Furniture; other manufactured goods n.e.c.",
                       "Secondary raw materials",
                       "Bottles for treatment, Recycling of bottles by direct reuse",
                       "Electricity by coal",
                       "Electricity by gas",
                       "Electricity by nuclear",
                       "Electricity by hydro",
                       "Electricity by wind",
                       "Electricity by petroleum and other oil derivatives",
                       "Electricity by biomass and waste",
                       "Electricity by solar photovoltaic",
                       "Electricity by solar thermal",
                       "Electricity by tide, wave, ocean",
                       "Electricity by Geothermal",
                       "Electricity nec",
                       "Transmission services of electricity",
                       "Distribution and trade services of electricity",
                       "Coke oven gas",
                       "Blast Furnace Gas",
                       "Oxygen Steel Furnace Gas",
                       "Gas Works Gas",
                       "Biogas",
                       "Distribution services of gaseous fuels through mains",
                       "Steam and hot water supply services",
                       "Collected and purified water, distribution services of water",
                       "Construction work",
                       "Secondary construction material for treatment, Re-processing of secondary construction material into aggregates",
                       "Sale, maintenance, repair of motor vehicles, motor vehicles parts, motorcycles, motor cycles parts and accessoiries",
                       "Retail trade services of motor fuel",
                       "Wholesale trade and commission trade services, except of motor vehicles and motorcycles",
                       "Retail  trade services, except of motor vehicles and motorcycles; repair services of personal and household goods",
                       "Hotel and restaurant services",
                       "Railway transportation services",
                       "Other land transportation services",
                       "Transportation services via pipelines",
                       "Sea and coastal water transportation services",
                       "Inland water transportation services",
                       "Air transport services",
                       "Supporting and auxiliary transport services; travel agency services",
                       "Post and telecommunication services",
                       "Financial intermediation services, except insurance and pension funding services",
                       "Insurance and pension funding services, except compulsory social security services",
                       "Services auxiliary to financial intermediation",
                       "Real estate services",
                       "Renting services of machinery and equipment without operator and of personal and household goods",
                       "Computer and related services",
                       "Research and development services",
                       "Other business services",
                       "Public administration and defence services; compulsory social security services",
                       "Education services",
                       "Health and social work services",
                       "Food waste for treatment: incineration",
                       "Paper waste for treatment: incineration",
                       "Plastic waste for treatment: incineration",
                       "Intert/metal waste for treatment: incineration",
                       "Textiles waste for treatment: incineration",
                       "Wood waste for treatment: incineration",
                       "Oil/hazardous waste for treatment: incineration",
                       "Food waste for treatment: biogasification and land application",
                       "Paper waste for treatment: biogasification and land application",
                       "Sewage sludge for treatment: biogasification and land application",
                       "Food waste for treatment: composting and land application",
                       "Paper and wood waste for treatment: composting and land application",
                       "Food waste for treatment: waste water treatment",
                       "Other waste for treatment: waste water treatment",
                       "Food waste for treatment: landfill",
                       "Paper for treatment: landfill",
                       "Plastic waste for treatment: landfill",
                       "Inert/metal/hazardous waste for treatment: landfill",
                       "Textiles waste for treatment: landfill",
                       "Wood waste for treatment: landfill",
                       "Membership organisation services n.e.c.",
                       "Recreational, cultural and sporting services",
                       "Other services",
                       "Private households with employed persons",
                       "Extra-territorial organizations and bodies"), 
                   "countries" = c("AT",
                                   "BE",
                                   "BG",
                                   "CY",
                                   "CZ",
                                   "DE",
                                   "DK",
                                   "EE",
                                   "ES",
                                   "FI",
                                   "FR",
                                   "GR",
                                   "HR",
                                   "HU",
                                   "IE",
                                   "IT",
                                   "LT",
                                   "LU",
                                   "LV",
                                   "MT",
                                   "NL",
                                   "PL",
                                   "PT",
                                   "RO",
                                   "SE",
                                   "SI",
                                   "SK",
                                   "GB",
                                   "US",
                                   "JP",
                                   "CN",
                                   "CA",
                                   "KR",
                                   "BR",
                                   "IN",
                                   "MX",
                                   "RU",
                                   "AU",
                                   "CH",
                                   "TR",
                                   "TW",
                                   "NO",
                                   "ID",
                                   "ZA",
                                   "WA",
                                   "WL",
                                   "WE",
                                   "WF",
                                   "WM"))