# Number of sectors and products in Exiobase 3
ThreeME.desc <- list("nProducts" = 28,
                     "products" =
                       c("Products of agriculture, Hunting, and Fishing",
                         "Products of Forestry",
                         "Food products and beverages",
                         "Motor vehicles, trailers and semi-trailers",
                         "Glass and ceramic products",
                         "Paper and paperboard",
                         "Chemicals",
                         "Plastics products",
                         "Metals",
                         "Other goods for industry",
                         "Other goods for consumers",
                         "Buildings and Civil engineering",
                         "Rail transport",
                         "Road transport",
                         "Water transport",
                         "Air transport",
                         "Business services",
                         "Public services",
                         "Non-energy mining",
                         "Coal",
                         "Crude oil",
                         "Transport fuels",
                         "Heating fuel",
                         "Natural gas",
                         "Electricity",
                         "Heat",
                         "Biomass",
                         "Other energy"),
                     "codes" =
                       c("cagr",
                         "cfor",
                         "cfoo",
                         "cveh",
                         "cgla",
                         "cpap",
                         "cche",
                         "cpla",
                         "cmet",
                         "cigo",
                         "ccgo",
                         "ccon",
                         "crai",
                         "croa",
                         "cwat",
                         "cair",
                         "cpri",
                         "cpub",
                         "cmin",
                         "ccoa",
                         "ccoi",
                         "cfut",
                         "cfuh",
                         "cgas",
                         "cele",
                         "chea",
                         "cbio",
                         "cote"))
