# Number of sectors and products in Exiobase 3
ThreeME_c29.desc <- list("nProducts" =    29,
                         "products"  =    c("Products of agriculture, Hunting, and Fishing",
                                            "Products of Forestry",
                                            "Food products and beverages",
                                            "Motor vehicles, trailers and semi-trailers",
                                            "Glass and ceramic products",
                                            "Paper and paperboard",
                                            "Chemicals",
                                            "Plastics products",
                                            "Metals",
                                            "Other goods for industry",
                                            "Other goods for consumers",
                                            "Buildings and Civil engineering",
                                            "Rail transport",
                                            "Road transport",
                                            "Water transport",
                                            "Air transport",
                                            "Business services",
                                            "Public services",
                                            "Non-energy mining",
                                            "Coal",
                                            "Crude oil",
                                            "Transport fuels",
                                            "Heating fuel",
                                            "Raw natural gas",
                                            "Distributed natural gas",
                                            "Electricity",
                                            "Heat",
                                            "Biomass",
                                            "Other energy"),
                         
                         "products.fr" =  c("Produits de l'agriculture, de la chasse et de la pêche",
                                            "Produits sylvicoles",
                                            "Produits alimentaires et boissons",
                                            "Véhicules automobiles, remorques et semi-remorques",
                                            "Minéraux non-métalliques",
                                            "Papier et carton",
                                            "Produits chimiques",
                                            "Produits en caoutchouc et en plastique",
                                            "Produits métallurgiques",
                                            "Autres produits pour l'industrie",
                                            "Autres produits de consommation",
                                            "Construction de bâtiments et de génie civil",
                                            "Transport ferroviaire",
                                            "Transport routier",
                                            "Transport fluvial",
                                            "Transport aérien",
                                            "Services privés",
                                            "Services publics",
                                            "Produit des industries extractives",
                                            "Charbon et produits du charbon",
                                            "Pétrole brut",
                                            "Carburants",
                                            "Fuel domestique",
                                            "Gaz naturel fossile",
                                            "Gaz naturel distribué",
                                            "Électricité",
                                            "Chaleur",
                                            "Biomasse",
                                            "Autres énergies"),
                         "codes" =        c("cagr",
                                            "cfor",
                                            "cfoo",
                                            "cveh",
                                            "cgla",
                                            "cpap",
                                            "cche",
                                            "cpla",
                                            "cmet",
                                            "cigo",
                                            "ccgo",
                                            "ccon",
                                            "crai",
                                            "croa",
                                            "cwat",
                                            "cair",
                                            "cpri",
                                            "cpub",
                                            "cmin",
                                            "ccoa",
                                            "ccoi",
                                            "cfut",
                                            "cfuh",
                                            "crga",
                                            "cdga",
                                            "cele",
                                            "chea",
                                            "cbio",
                                            "cote"))
